name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.2+12

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.0.8
  url_strategy: ^0.3.0
  pin_code_fields: ^8.0.1


  geolocator: ^14.0.2
#  geolocator: ^11.0.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.5.12
  flutter_typeahead: ^5.2.0
  carousel_slider: ^5.1.1
#  shimmer_animation: ^2.2.2
  image_picker: ^1.1.2
#  universal_html: ^2.0.8
#  universal_ui: ^0.0.8
  flutter_inappwebview: ^6.1.5
  flutter_widget_from_html_core: ^0.16.0
  url_launcher: ^6.0.17
  http:
  pointer_interceptor: ^0.10.1+2
  phone_number: ^2.1.0
  country_code_picker: ^3.3.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+4
  flutter_facebook_auth: ^7.1.2
  photo_view: ^0.15.0
  dotted_border: ^2.0.0+2
  share_plus: ^11.0.0
  custom_map_markers: ^0.0.2+1
  permission_handler: ^12.0.1



#  image_compression_flutter: ^1.0.4
  fwfh_text_style: ^2.23.0
  card_swiper: ^3.0.1
  expandable_bottom_sheet: ^1.1.1+1
  app_links: ^6.4.0
  modal_bottom_sheet:
  sign_in_with_apple: ^7.0.1
#  sign_in_with_apple: ^4.3.0
  flutter_svg: any

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  geolocator_android: 4.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900